version: '3.3'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    expose:
      - ${TYPEORM_PORT}
    networks:
      - webnet

  api:
    build: ./
    volumes:
      - .:/apps/highway-access-api
      - /apps/highway-access-api/node_modules
    command: npm run start:dev
    env_file:
      - .env
    links:
      - db
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    networks:
      - webnet

networks:
  webnet:

volumes:
  mysql_data: