version: '3.8'
services:
  api:
    container_name: highway-access-api
    build: ./
    volumes:
      - .:/apps/highway-access-api
      - /apps/highway-access-api/node_modules
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    networks:
      - webnet

  db:
    container_name: mysqldb
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    stdin_open: true
    tty: true
    networks:
      - webnet

networks:
  webnet:

volumes:
  mysql_data: